language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
install:
  - pip install ".[test]" . # install package + test dependencies
script: python -m pytest --cov=skbel
after_success:
  - codecov # submit coverage
